#!/usr/bin/env bash
# upgrade-clux.sh — upgrade an installed clux to the version of this plugin
# tree, with no questions. /clux:upgrade runs it.
#
# The answers of the last /clux:setup are all in ~/.config/clux/clux.tmux.conf.
# render-clux-conf.sh --from reads them back, and writes the file again with
# this version: a setting this version added gets its default, and a setting
# it removed is reported as "dropped:". This script renders first, so a
# render failure changes nothing. Then it backs up the file, deploys the
# scripts from the manifest, puts the new file in place, verifies it on a
# throwaway server, and reloads it. A failure after the backup puts the
# backup back.
#
# It does not change the user's tmux.conf or ~/.claude/settings.json. It only
# reports when the tmux.conf does not have the clux line or the two tokens.
#
# Usage: upgrade-clux.sh [--no-reload] [--conf PATH] [--scripts-dir PATH]
#                        [--tmux-conf PATH] [-- RENDER_FLAGS...]
#
#   --no-reload   do not source the new file into the running tmux server
#   -- FLAGS      more render-clux-conf.sh flags, after --from (a later flag
#                 wins). /clux:upgrade uses this for a required answer that
#                 the old file does not have
#
# Exit codes:
#   0  upgraded
#   2  usage error
#   3  no clux.tmux.conf that /clux:setup made: run /clux:setup
#   4  a required answer is missing: one "missing: --<flag>" line each
#   5  the new file did not verify; the backup is back in place
#   6  a step failed (render, backup or deploy); nothing changed, or the
#      backup is back in place

set -uo pipefail

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RENDER="$CURRENT_DIR/render-clux-conf.sh"
VERIFY="$CURRENT_DIR/verify-tmux-conf.sh"
MANIFEST="$CURRENT_DIR/../config/deploy-manifest.txt"

CONF="$HOME/.config/clux/clux.tmux.conf"
SCRIPTS_DIR="$HOME/.config/clux/scripts"
TMUX_CONF=""
RELOAD=1
EXTRA=()

while [ $# -gt 0 ]; do
    case "$1" in
        --no-reload) RELOAD=0; shift ;;
        --conf) CONF="${2:-}"; shift 2 ;;
        --scripts-dir) SCRIPTS_DIR="${2:-}"; shift 2 ;;
        --tmux-conf) TMUX_CONF="${2:-}"; shift 2 ;;
        --) shift; EXTRA=("$@"); break ;;
        -h|--help) sed -n '2,32p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "upgrade-clux.sh: unknown argument: $1" >&2; exit 2 ;;
    esac
done

FIRST=""
[ -f "$CONF" ] && IFS= read -r FIRST < "$CONF"
case "$FIRST" in
    *'generated by /clux:setup'*) ;;
    *) echo "needs-setup: $CONF is missing or was not made by /clux:setup"; exit 3 ;;
esac

# "# ... generated by /clux:setup (clux 4.3.0)" -> 4.3.0
_version_of() { sed -n '1s/.*(clux \([^)]*\)).*/\1/p' "$1"; }
FROM=$(_version_of "$CONF")

NEW="$(mktemp "${CONF}.new.XXXXXX")" || { echo "error: cannot write next to $CONF" >&2; exit 6; }
LOG="$(mktemp "${CONF}.log.XXXXXX")" || { rm -f "$NEW"; echo "error: cannot write next to $CONF" >&2; exit 6; }
trap 'rm -f "$NEW" "$LOG"' EXIT

if ! "$RENDER" --from "$CONF" ${EXTRA[@]+"${EXTRA[@]}"} \
        --scripts-dir "$SCRIPTS_DIR" --out "$NEW" >/dev/null 2>"$LOG"; then
    if grep -q '^missing: ' "$LOG"; then
        grep '^missing: ' "$LOG"
        exit 4
    fi
    cat "$LOG" >&2
    echo "error: render-clux-conf.sh failed; nothing changed" >&2
    exit 6
fi
DROPPED=$(sed -n 's/^render-clux-conf.sh: dropped: //p' "$LOG")

# Back up. Keep the five newest backups, the same as /clux:setup.
BACKUP_DIR="$(dirname "$CONF")/backups"
mkdir -p "$BACKUP_DIR"
BACKUP="$BACKUP_DIR/clux.tmux.conf.$(date +%Y%m%d_%H%M%S)"
cp "$CONF" "$BACKUP" || { echo "error: cannot back up $CONF; nothing changed" >&2; exit 6; }
ls -1t "$BACKUP_DIR"/clux.tmux.conf.* 2>/dev/null | tail -n +6 | while IFS= read -r old; do rm -f "$old"; done

# _fail CODE MESSAGE — put the backup back and stop.
_fail() {
    cp "$BACKUP" "$CONF"
    echo "error: $2; the backup is back in place" >&2
    exit "$1"
}

# Deploy from the manifest, the one list of deployed scripts.
mkdir -p "$SCRIPTS_DIR"
n=0
for s in $(grep -v '^[[:space:]]*#' "$MANIFEST" | grep -v '^[[:space:]]*$'); do
    cp "$CURRENT_DIR/$s" "$SCRIPTS_DIR/$s" && chmod +x "$SCRIPTS_DIR/$s" || _fail 6 "cannot deploy $s"
    n=$((n + 1))
done

mv "$NEW" "$CONF" || _fail 6 "cannot write $CONF"

# To a file, never through $( ): verify-tmux-conf.sh leaves a control client
# in the background, and a command substitution waits for it.
if ! "$VERIFY" "$CONF" >"$LOG" 2>&1 </dev/null; then
    cat "$LOG" >&2
    _fail 5 "the new clux.tmux.conf did not verify"
fi

echo "from: ${FROM:-unknown}"
echo "to: $(_version_of "$CONF")"
echo "scripts: $n deployed to $SCRIPTS_DIR"
echo "conf: $CONF"
echo "backup: $BACKUP"
for d in $DROPPED; do echo "dropped: $d (this version has no such setting)"; done

# The user's tmux.conf: report only, never change.
if [ -z "$TMUX_CONF" ]; then
    for c in "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" "$HOME/.tmux.conf"; do
        [ -f "$c" ] && { TMUX_CONF="$c"; break; }
    done
fi
if [ ! -f "$TMUX_CONF" ]; then
    echo "warn: no tmux.conf found"
else
    grep -q 'source-file.*clux\.tmux\.conf' "$TMUX_CONF" \
        || echo "warn: $TMUX_CONF has no source-file line for clux.tmux.conf"
    for t in '#{@clux_session_bar}' '#{@clux_status}'; do
        grep -qF "$t" "$TMUX_CONF" || echo "warn: $TMUX_CONF has no $t token"
    done
fi

if [ "$RELOAD" -eq 1 ] && tmux info >/dev/null 2>&1; then
    if tmux source-file "$CONF" 2>/dev/null; then
        echo "reloaded: yes"
    else
        echo "warn: tmux could not source $CONF; run: tmux source-file $CONF"
    fi
else
    echo "reloaded: no"
fi
